version: "3.7"

services:
  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ${PWD}/config/sonarr:/config
      - ${TORRENT_DIR}:/downloads
      - ${MEDIA_DIR}:/media
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.middlewares=auth@file, securityHeaders@file"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"

networks:
  traefik_proxy:
    external: true