version: "3.7"

services:
  traefik:
    hostname: traefik
    image: traefik
    container_name: traefik
    restart: always
    domainname: ${DOMAIN_NAME}
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/traefik:/etc/traefik:ro
  #  environment:
  #    - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
  #    - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.middlewares=auth@file, securityHeaders@file"

networks:
  traefik_proxy:
    external: true