version: "3.7"

services:
  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - ${PWD}/config/radarr:/config
      - ${TORRENT_DIR}:/downloads
      - ${MEDIA_DIR}:/media
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.middlewares=auth@file, securityHeaders@file"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"

networks:
  traefik_proxy:
    external: true