version: "3.7"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ${PWD}/config/jackett:/config
      - ${TORRENT_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett.middlewares=securityHeaders@file"
      - "traefik.http.routers.jackett.tls.certresolver=letsencrypt"

networks:
  traefik_proxy:
    external: true