version: "3.7"

services:
  traefik:
    hostname: traefik
    image: traefik:1.6
    container_name: traefik
    restart: always
    domainname: ${DOMAIN_NAME}
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/traefik/traefik.toml:/traefik.toml:ro
      - ${PWD}/config/traefik/acme.json:/acme.json
   environment:
     - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
     - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_NAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAIN_NAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
      - "traefik.frontend.auth.basic.users=${HTTP_AUTH_USERNAME}:${HTTP_AUTH_PASSWORD}"

networks:
  host:
  traefik_proxy:
    external: true
  default:
    driver: bridge